server:
  port: 8088

spring:
  application:
    name: lojaAuth
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaServer:8761/eureka
