server:
  port: 5555

spring:
  application:
    name: lojagateway

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
