spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h21

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:supplierinfo;DB_CLOSE_DELAY=-1
    username: supplierinfo
    password: supplierinfo
