spring:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/supplierinfo
    username: supplierinfo
    password: supplierinfo
