server:
  port: 8081
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/supplierinfo
    username: supplierinfo
    password: supplierinfo

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user
